openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io/v2'
info:
  description: >-
    :dog: :cat: :rabbit: This is a sample server Petstore server.  You can find
    out more about Swagger at [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you
    can use the api key `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
paths:
  /client_code_gen:
    post:
      summary: client代码生成
      description: 根据openapi yaml文件生成client代码
      parameters:
        - name: generator_name
          in: query
          required: true
          schema:
            type: string
          description: 生成器名称，使用GET /code_genenerators获取枚举
        - name: package_name
          in: query
          required: false
          schema:
            type: string
            default: client
          description: 代码包名称
          allowEmptyValue: true
      operationId: Generate client code
      responses:
        default:
          description: Default response
  /code_genenerators:
    get:
      summary: 获取代码生成器名称列表
      description: 获取代码生成器名称列表
      parameters: []
      operationId: get client code generators
      responses:
        default:
          description: Default response
  /doc_generators:
    get:
      summary: 获取文档生成器名称列表
      description: 获取文档生成器名称列表
      parameters: []
      operationId: Get doc generators
      responses:
        default:
          description: Default response
  /doc_gen:
    post:
      summary: 生成文档
      description: 根据openapi yaml文件生成接口文档
      parameters:
        - name: generator_name
          in: query
          required: true
          schema:
            type: string
          description: 生成器名称，使用GET /doc_generators获取枚举
      operationId: generate doc
      responses:
        default:
          description: Default response
      requestBody:
        required: false
        content:
          application/yaml:
            schema: {}
        description: 上传的OPEN-API yaml配置文件
externalDocs:
  description: See AsyncAPI example
  url: 'https://mermade.github.io/shins/asyncapi.html'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    Pet:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
        application/xml:
          schema:
            $ref: '#/components/schemas/Pet'
      description: Pet object that needs to be added to the store
      required: true
    UserArray:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'
      description: List of user object
      required: true
  securitySchemes:
    x-access-username:
      type: apiKey
      name: x-access-username
      in: header
    x-access-token:
      type: apiKey
      name: api_key
      in: header
  links: {}
  callbacks: {}
security: []